services:
  metube:
    image: alexta69/metube:latest
    restart: unless-stopped
    ports:
      - "8080:8081"
    volumes:
      - /opt/hometools/data/metube:/downloads
    environment:
      DELETE_FILE_ON_TRASHCAN: "true"
      YTP_METADATA: "false"
      YTDL_OPTIONS: '{"writethumbnail": false, "writeinfojson": false, "addmetadata": false}'
      YTP_POSTPROCESSOR_ARGS: "ffmpeg:-map_metadata -1 -fflags +bitexact -flags:v +bitexact -flags:a +bitexact"

  stirling-pdf:
    image: ghcr.io/stirling-tools/stirling-pdf:latest
    restart: unless-stopped
    ports:
      - "8081:8080"